### PR TITLE
[BUGFIX] Don't upgrade on Debian 6

### PR DESCRIPTION
**Pull request by StephenKing**
Chef 12.19.36 is the last release available for Debian 6.

### CODE REVIEW

**Comment by StephenKing** [comment]
Couldn't make `kitchen-dokken` (Docker-based testing) work with Debian 6, only using Vagrant.

**Comment by stucki** [comment]
Hmm, so they removed Debian 6 support somewhere between 12.19.36 and 12.21.3? That's imho a really bad practice done by Chef. I would prefer if they would stick to http://semver.org/...

Nevertheless, your patch looks good. Thanks for the fix!

**Review by stucki — APPROVED** [review]

**Comment by stucki** [comment]
(Sidenote: Would you like to merge such changes on your own or should I just do it when the review is fine? What workflow do you prefer?)

**Comment by StephenKing** [comment]
Depends  on the situation, I would say. For changes like this one, I'd be super fine if you merge it. Let's maybe try to write down such request in the PR.

Anyways, it would be nice if other team members would have a look (and have some time to do so) as well.

**Pull request merged**
